### ISSUE TITLE
Add Request timeout config

### ISSUE THREAD

**Issue by ortegadany** [hboie/JasperReportBundle#1]
Hi, its be good add a timeout parameter in the file setting  to set the request timeout on client , now is default to 30sec

example:

hboie_jasper_report:
    host:      '%env(resolve:JASPER_SERVER_HOST)%'
    username:  '%env(resolve:JASPER_ADMIN_USER)%'
    password:  '%env(resolve:JASPER_ADMIN_PASSWORD)%'
    org_id:    null
    timeout: 300

**Comment by mathvicot15** [comment]
It might be a good idea. Queries tend to timeout when I generate a report with a lot of data.

**Comment by hboie** [comment]
Yes, good idea! I will try to implement this soon...

**Comment by hboie** [comment]
I added the timeout option in the configuration as suggested in release v1.6
I would be grateful if you could check if it works fine and helps you.

Best regards,

hboie

**Comment by hboie** [comment]
The suggested function was implemented in release v1.6. Therefore I close this issue.

Thank you very much for helping to improve - if you like our work, please don't forget to leave a star!

Best regards,

hboie
