### ISSUE TITLE
Error when use function Search repository by criteria

### ISSUE THREAD

**Issue by Graalstrike** [hboie/JasperReportBundle#3]
Hello,
In "jasper-rest-client/src/jaspersoft/Service/RepositoryService.php", on line 69, the "$headers['Result-Count']" and "$headers['Start-Index']" parameters called cause an error.
You must write the keys without uppercase for the function to pass: "$headers['result-count']" and "$headers['start-index']".
Other than that, thank you for the great job on this bundle. 

Cordially, 

System Ubuntu 20.04, Apache2, PHP 7.4, symphony 5.4

**Comment by hboie** [comment]
Dear Graalstrike,

thank you very much for your feedback. I did not have this problem so far, so I tried to make the code more stable by allwoing both indexes:

        if( isset($headers['Result-Count']) )
            $resultCount = (int) $headers['Result-Count'];
        else if( isset($headers['result-count']) )
            $resultCount = (int) $headers['result-count'];
        else
            $resultCount = 0;

        if( isset($headers['Start-Index']) )
            $startIndex = (int) $headers['Start-Index'];
        else if( isset($headers['Start-Index']) )
            $startIndex = (int) $headers['Start-Index'];
        else
            $startIndex = 0;

It seems to work for me, so please check, if it also works for you.

By the way: In fact the code is not part of the hboie/JasperReportBundle but of the  hboie/JasperRestClient which is a dependency of the hboie/JasperReportBundle - so we now have a new version v1.1 of the hboie/JasperRestClient.

Best regards,

Hans

**Comment by Graalstrike** [comment]
Hello,
Everything seems to be working fine on my end.

Thank you very much for your responsiveness.

**Comment by hboie** [comment]
Hello Graalstrike,

Thank you very much for helping to improve the package!

This issue seems to solved, so I close it.

Best regards,

Hans
